import turtle as t

t.hideturtle()
t.color("blue")
t.speed(1)
t.begin_fill()
t.circle(70)
#t.showturtle()
t.fillcolor("red")
t.end_fill()
t.filling()
t.screensize(10, 3300)
t.isvisible()
t.penup()
t.setx(-10)
t.sety(70)
t.pendown()
t.write("Richard", font=("Arial", 12, "normal"))

#t.clear()
#t.reset()
t.done()